# Generated by Django 3.1.8 on 2021-06-08 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versioning.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, default='', max_length=2048, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to=versioning.models.upload_to)),
                ('revision_url', models.CharField(blank=True, max_length=2048)),
                ('index', models.IntegerField(blank=True, default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='versioning.document')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
